### ISSUE TITLE
Font too small/different for Thumbnail view

### ISSUE THREAD

**Issue by richardtallent** [mcmonkeyprojects/SwarmUI#102]
### Expected Behavior

The Thumbnail mode for the Bottom Bar tab content offers the most space-compact view, but the font is absolutely tiny, and is in a monospace font, unlike the rest of the UI. Even smaller than the "current-image-data" area, which is already tiny. And I'm using a 4K 30" monitor zoomed to 110%.

### Actual Behavior

For accessibility and legibility, font faces and sizes should be largely uniform across a UI. Otherwise it makes it impossible to adjust the UI so text is legible without other text

# Screaming at you in large sizes :)

The font face should especially be consistent. Some situations call for a monospace font, such where where whitespace counting is needed or text needs to line up vertically. That's not really the case here.

*Another minor related issue*

The thumbnail label currently includes the full path to the file. This is helpful when viewing the Root folder, but when you've already selected that folder on the left, it's just wasted space. Showing paths only as relative to the selected folder under the Root would help alleviate the need to limit the size of the text.

### Steps to Reproduce

In the bottom bar, go to Models, LoRAs, Embeddings, etc. Choose Thumbnails mode.

Note the font size of 9.8 pixels, and how this to compares to the larger text on-screen -- the Generate button, top menu, and bottom bar tabs (more than twice as large, 20px). Even the tiny text in the "current image data" area is 12px.

### Debug Logs

```powershell
n/a
```

### Other

~~I recommend using CSS variables for common things like font sizes and faces, so the CSS across the board is more consistent without having to keep it all aligned manually or through complex cascading.~~ (I just poked through the source and saw that you are using CSS vars)

**Comment by mcmonkey4eva** [comment]
Thumbnail view was intended for the image browser
![image](https://github.com/user-attachments/assets/dfc1cfac-3d43-432d-be8d-f1806058dc09)

Names are long and direct value of the names is low/rare, so them occupying too much space is unwanted.

I'm probably gonna make an even denser image gallery variant in the near future, as currently the image gallery is way too whitespacey for my personal taste.

Maybe for thumbnail view, it could be made a bit more dynamic - shrink if the names are very long, and display normal size if not too long.

... The part you mentioned of subsetting the name to only the part after what folder you're in, is, uh... already working on the image browser. It's indeed missing from the model view tho, so that's a pure and simple bug

**Comment by mcmonkey4eva** [comment]
- Improved line-splitting on browser text
- Fix the stray pathnames on model names
- Fixed bounding boxes
- Applied the dynamic size change for thumbnail names mentioned above
