### ISSUE TITLE
SDXL 1024x1024 1 step speed is 5.14s/it on RTX 4080 SUPER 

### ISSUE THREAD

**Issue by FurkanGozukara** [mcmonkeyprojects/SwarmUI#280]
### Expected Behavior

SwarmUI v0.9.2.3 (2024-09-23 10:35:14

First generation speed is 5 it second and it slows down to 5 second it

Here full verbose logs

https://paste.denizenscript.com/View/126753

here screenshots

![image](https://github.com/user-attachments/assets/322cbdab-520e-4b76-90b1-c1a30a421f02)

![image](https://github.com/user-attachments/assets/d1686258-de22-4e52-9aa5-bcc8620fde4b)

![image](https://github.com/user-attachments/assets/e7bcbb4f-81e8-4215-8c9e-a647027dae8a)

![image](https://github.com/user-attachments/assets/006d25b1-7ab2-4590-8873-52ee15422deb)

**Comment by FurkanGozukara** [comment]
@mcmonkey4eva i mean look at this speed drop

https://paste.denizenscript.com/View/126754

![image](https://github.com/user-attachments/assets/af63246d-d351-4143-aa4c-4a124b472431)

**Comment by mcmonkey4eva** [comment]
- double check your backends are correct. You might've accidentally put multiple on the same GPU_ID, so they're using the same compute resources.
- If not that, then... restart in a relatively clean env and with default params to reduce variables, it's possible some specific installed node pack or setting or etc. is having a negative side effect here.
- It's extremely unlikely to be a core issue, but if it is, almost certainly an issue with the ComfyUI backend rather than SwarmUI
