### ISSUE TITLE
setup and run custom workflow via API

### ISSUE THREAD

**Issue by jjsapido** [mcmonkeyprojects/SwarmUI#383]
### Your question

As title suggest I’m trying to remotely access  swarmui, im currently using pythona as: requests.post(url, data=json_string, headers=headers)

Example 1 - Success
If I access swarmui standard parameters, the api work well and everything behave correctly afaik
    self.data = {
        "session_id": "",
        "prompt": "",
        "negativeprompt": "",
        "seed": "-1",
        "steps": "20",
        ...
        }

Example 2 - Errore
But I  can’t find a way to acces custom workflow and their custom nodes parameters
        self.data = {
            "textcliptextencodepositivepromptnodetextg":"custom node prompt",
            "session_id": "",
            "height": "1024",
            "width": "1024",
            "model": "xxx",
            "comfyuicustomworkflow": "custom_workflow_v1",
            "dropdownbasicschedulernodeschedulerr": "simple",
            ...
            }
If I send that request and anlyze the image generated from the gui there's no workflow applied nor any custom parameter (like textcliptextencodepositivepromptnodetextg) gets properly elaborated by the server   

I tried to resort to documentation but I didn’t find anything and it seems still under construction in many parts and other completely omitting this scenario. 
I’m wondering if it’s just not supported yet or there’s a workaround to be able to  directly call from API a custom workflow or pass a json custom workflow via api and set come custom nodes parameters as well. 

Thanks for any hint

**Comment by mcmonkey4eva** [comment]
The API around this is a little weird atm and needs improvement still, for now -- go in the interface, set up your workflow, click "use this workflow in generate tab", configure whatever, and open your browser console to view network traffic, and hit Generate. It'll open a websocket and the first message on it will be the generation parameters. It currently sends two special parameters: the raw workflow with parameter adaptations, and the parameter metadata.

In the future I intend to swap this to work automatically closer to the way you were trying in your "Example 2", where you just give the ID and it loads the workflow serverside and figures that all out. It's just been low priority since that's a rather uncommon use case.
