### ISSUE TITLE
LoHa trained in Onetrainer don't work with error "ComfyUI execution error: self must be a matrix"

### ISSUE THREAD

**Issue by 8bit-boom** [mcmonkeyprojects/SwarmUI#481]
### Expected Behavior

Should generate image with selected LoHa.

### Actual Behavior

Image isn't generated, instead error "ComfyUI execution error: self must be a matrix"

### Steps to Reproduce

1. Open SwarmUI
2. Choose SDXL model (in my case it was PonyXL)
3. Click generate model (using standard settings)
4. Error will appear 

<img width="2034" alt="{CAA5B8D4-0F5B-4D96-8B20-628F0CC4E215}" src="https://github.com/user-attachments/assets/87b7417b-6825-4bc3-8b90-5d62dd294d2b" />

### Debug Logs

https://paste.denizenscript.com/View/129211

### Other

I am using personal LoHa trained in Onetrainer, it works with Automatic1111 and Forge, but gives error in SwarmUI. Found similar issue in OneTrainer  github "https://github.com/Nerogar/OneTrainer/issues/525".

**Comment by mcmonkey4eva** [comment]
oh, if it's a specific new custom trainable type and not a well known model variant, it might not yet be supported in ComfyUI (which is the backend that powers Swarm), so, yeah, that issue you linked will have to be resolved first.

Since you're doing custom training, I'd recommend just using a more well established model type

**Comment by 8bit-boom** [comment]
I just want to add, that I tried LoRa trained on same model in Onetrainer and it works, so if somebody have same issue, than solution is to retrain it to LoRa instead of LoHa.
