### ISSUE TITLE
Generations using the same seed and parameters in LTXV I2V are not fully deterministic

### ISSUE THREAD

**Issue by rc-gr** [mcmonkeyprojects/SwarmUI#491]
### Expected Behavior

Videos generated using the same seed and parameters should be identical.

### Actual Behavior

Discrepancies are found between repeated generations using the same seed and parameters. This issue is present when using either 0.9 or 0.9.1.

Seed 1 (eg. moon at the top-right is skewed differently)

https://github.com/user-attachments/assets/d96887a2-9e19-496d-a364-64a974e9d02e

https://github.com/user-attachments/assets/a12c900c-0a87-4fc2-8008-e1602ffdb580

Seed 10 (eg. moon at the top-right goes missing at the end in the first video, but does not in the second):

https://github.com/user-attachments/assets/dfeb14ec-90b4-4040-b6f2-0e1857331e20

https://github.com/user-attachments/assets/3657db02-806c-484c-bc8d-9a8f1824b9f8

### Steps to Reproduce

Prerequisites: 
-  LTXV v0.9 or v0.9.1 loaded and working from [Hugging Face](https://huggingface.co/Lightricks/LTX-Video/tree/main). This example will use v0.9.1.

Setup:
1.  Use the image from here: https://en.wikipedia.org/wiki/The_Starry_Night#/media/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg
2.  Download and import this preset: [starry_night.json](https://github.com/user-attachments/files/18239426/starry_night.json)
3. Drag-and-drop the image to Generate's main window and Use As Init.
4. Check that Core Parameters > Seed is 1, then hit Generate.
5. Change Seed to another value, 10 in this example, then hit Generate.
6. Change Seed back to 1, then hit Generate.
7. Change Seed back to 10, then hit Generate.
8. Compare the video results.

### Debug Logs

https://paste.denizenscript.com/View/129308

### Other

This issue does not seem to be present when using the model's T2V features.

**Comment by rc-gr** [comment]
I just did a test using LTXV's example workflow from [here](https://github.com/Lightricks/ComfyUI-LTXVideo/blob/master/assets/ltxvideo-i2v.json). Modified it to use my own captioning: 
[LTXVideo.json](https://github.com/user-attachments/files/18240025/LTXVideo.json)
(image example: `https://www.aspca.org/sites/default/files/cat-care_general-cat-care_body1-left.jpg`)

When I change the RandomNoise `noise_seed` from one value to another and back, I get identical results as expected. This was done using the same Comfy backend that Swarm was using in this issue.

**Comment by mcmonkey4eva** [comment]
I'd guess this is microvariation chaos (the butterfly effect) -- ie, a very very tiny change is happening unintentionally somewhere, and across the billions of calculations producing an entire video out it, that difference expands into something visible. This happens all the time, even in regular image generation, it's just usually the final result is a slight color shift in a few pixels, not enough to matter.

The reason this would happen more in Swarm's interface than in a comfy workflow, is there's a few extra steps happen.
To see the dirty details, set up your gen, then click the Comfy tab, and click Import from Generate Tab
![image](https://github.com/user-attachments/assets/083f0060-3125-4a30-9ee6-9400cece7bfa)
`(A)` Swarm does its own scaling of the input image. Your source is 2560x2027, and it needs to be shrunk to the appropriate resolution. This should be consistent, but I wouldn't be surprised if a there was a 0.01 color difference on a pixel or two. This doesn't get cached currently.
`(C)` Because of the dirty trick of the Init Image with Creativity 0, it's not actually directly fed to the video model, it hits a sampler of the base model first. This, luckily, actually does nothing, but:
`(B)` it does go through a VAE Encode + Decode despite the lack of any actual processing. This is something I want to change because it's dumb, it's just a temporarily limitation.

Pending that getting fixed, you might reduce the differences by just changing the base model selection, some VAEs are more stable than others. Flux is high detail but has color space shifting. SDXL is very stable with weakened detail reproduction.

(Or, of course, also a valid option: as long as the differences are very small and only visible in chaos swirls, ignore it, cause if you want such perfect control you shouldn't be using AI lol. Add a single random character to the prompt and you'll get a bigger change than this).

You might also consider the models in use. Notably Swarm by default uses a T5XXL model in fp8 format, which is a tiny bit less stable than an fp16 copy of T5. There's a parameter under Advanced to switch the preferred T5 model.

If you tested comfy by launching it separately, you might also want to test it inside the comfy tab on Swarm. Swarm by default adds a few launch args, notably including `--fast` which tells Comfy to use faster (but slightly less stable) fp8 multiplications when it can.
There is a server config option to disable that if it's the cause of the differences:
![image](https://github.com/user-attachments/assets/c5dee5f9-5d75-4266-bf81-eeaa47566aea)

**Comment by rc-gr** [comment]
@mcmonkey4eva Ok, I did more testing according to what you suggested, just shy of disabling `--fast` (which would unnecessarily increase generation times). From what I could tell, it turns out that `image_noise_scale` from Comfy's `LTXVImgToVideo` is the most likely culprit for the deviation (which just so happens to be unused by Lightrick's workflow).

Referring to this pack of sample outputs:
[LTXVSwarm_NoiseIssue.zip](https://github.com/user-attachments/files/18243301/LTXVSwarm_NoiseIssue.zip)

(Note: MPC throws some "encountered an improper argument" error, probably because of how I'm just casually swapping in the Video Combine node as-is. You'll need to use some other player like VLC or XnView.)
- Default is Swarm's default workflow (minus the Video Combine at the end). (2) is a rerun of (1)'s exact workflow.
- BaseNoiseOff is Default plus setting `image_noise_scale` from Comfy's `LTXImgToVideo` to `0.0`. Additionally, for the sake of ruling out, `add_noise` from `(C)` is set to `false` for (1) and (2), but reverted to `true` for (3).
- `(A)` is not considered here as it did not affect the test in any meaningful way whatsoever. The picture from `https://www.aspca.org/sites/default/files/cat-care_general-cat-care_body1-left.jpg` is used as-is.

As you can see, for Default, for seed 84, the cat turns its head far more towards the left of the image for (2) vs (1). And for 86, it's far worse - almost no movement on (2) vs (1). This is definitely way more than "very small" differences.

In contrast, when I set `image_noise_scale` to `0.0`, I get consistent results for both seeds (still with a different result per seed), down to the byte in file size.

I believe it has something to do with this line, based on how `image_noise_scale` is being passed around. But I can't figure out exactly what's causing the randomness in the `randn` call, be it a random seed, time-based, or other:
https://github.com/comfyanonymous/ComfyUI/blob/99a1fb6027b7163592a83669b0b1c5aa4657c2b6/comfy/ldm/lightricks/model.py#L447

On that note, I wonder if `image_noise_scale` can be exposed to the UI as an advanced setting. Otherwise, maybe the value should default to `0.0` instead so the model's behavior is more in line, as least in terms of predictability, with Lightrick's workflow.

**Comment by mcmonkey4eva** [comment]
oh, Swarm's generate tab has that filed under the `Video Augmentation Level` param, I defaulted it to `0.15` in LTX-V because that's the LTX-V default image_noise_scale value. (Though it seems to kinda suck so maybe it should be 0.)
You should probably report on the comfy github that its not seeded properly. Which... yeah, it seems to be written in such a way that it initializes from random static seed `42` and then changes each time you call it? Which... what? That's really weird.
