### ISSUE TITLE
Option to Choose Between FreeU v1 and FreeU v2

### ISSUE THREAD

**Issue by 0xHomunculus** [mcmonkeyprojects/SwarmUI#73]
### Feature Idea

By default SwarmUI uses the original v1 implementation of FreeU. There exists a newer FreeU v2 implementation that makes some changes to the original with the aims of improving accuracy and efficiency. The functionality for this new implementation seems to be provided in the FreeU_v2 node in comfyUI. Being able to choose which version of FreeU is to be used would be a great quality of life feature for those who rely on it for their workflows.

**Comment by mcmonkey4eva** [comment]
`a photo of a cat` seed 1, SDXL base, FreeU v1
![1525-a photo of a cat-sd_xl_base_10-1-1](https://github.com/user-attachments/assets/61df1cff-0da7-4310-93cd-f62345c226e2)
FreeU v2
![1525-a photo of a cat-sd_xl_base_10-1-3](https://github.com/user-attachments/assets/ac671427-09ca-42e3-8a46-bd58364b7c8a)

------------

I post this here because, uh, I found a comfy bug while testing :) oops. If you toggle just v1/v2 (ie nothing changes but the type of a node), ComfyUI accidentally caches the value and doesn't regenerate, so it was actually a bit of effort to smack the cache away and carefully regenerate the same image with only that param changed.
I thought at first it didn't even work until I discovered that.

----

Anyway, param added
![image](https://github.com/user-attachments/assets/34205ee0-8551-4aab-b6cd-98b97ebcf64b)
